'use client';

import { useState } from 'react';
import type { ChatMessage, IndexNode } from '@/app/data/structures';
import styles from './ChatPanel.module.css';

interface ChatPanelProps {
  selectedSections: Set<string>;
  indexNodes?: IndexNode[];
}

function getSectionTitle(id: string, nodes: IndexNode[]): string {
  const findTitle = (searchNodes: IndexNode[]): string | null => {
    for (const node of searchNodes) {
      if (node.id === id) return node.title;
      if (node.children) {
        const found = findTitle(node.children);
        if (found) return found;
      }
    }
    return null;
  };
  return findTitle(nodes) || id;
}



export default function ChatPanel({ selectedSections, indexNodes = [] }: ChatPanelProps) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');

  const handleSend = () => {
    if (!input.trim()) return;

    const userMsg: ChatMessage = {
      id: `m${Date.now()}`,
      role: 'user',
      content: input,
    };

    const assistantMsg: ChatMessage = {
      id: `m${Date.now() + 1}`,
      role: 'assistant',
      content: 'This is a mock response. In the real app, this would be generated by the RAG system based on the indexed document content.',
    };

    setMessages([...messages, userMsg, assistantMsg]);
    setInput('');
  };

  return (
    <div className={styles.panel}>
      {selectedSections.size > 0 && (
        <div className={styles.context}>
          <span className={styles.contextLabel}>Context:</span>
          {Array.from(selectedSections).slice(0, 3).map(id => (
            <span key={id} className={styles.contextChip}>
              {getSectionTitle(id, indexNodes).substring(0, 20)}...
            </span>
          ))}
          {selectedSections.size > 3 && (
            <span className={styles.contextMore}>+{selectedSections.size - 3} more</span>
          )}
        </div>
      )}

      <div className={styles.messages}>
        {messages.map(msg => (
          <div key={msg.id} className={`${styles.message} ${styles[msg.role]}`}>
            <div className={styles.messageRole}>{msg.role === 'user' ? 'You' : 'Assistant'}</div>
            <div className={styles.messageContent}>{msg.content}</div>
          </div>
        ))}
      </div>

      <div className={styles.inputArea}>
        <input
          type="text"
          className={styles.input}
          placeholder="Ask about the document..."
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && handleSend()}
        />
        <button className={styles.sendBtn} onClick={handleSend}>
          Send
        </button>
      </div>
    </div>
  );
}
